name: psiml
channels:
  - pytorch
  - willyd
  - conda-forge
  - defaults
dependencies:
  - blas=2.16=mkl
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cudatoolkit=10.2.89=h74a9793_1
  - freetype=2.10.2=hd328e21_0
  - intel-openmp=2020.1=216
  - jpeg=9d=he774522_0
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libopencv=3.4.2=h20b85fd_0
  - libpng=1.6.37=hfe6a214_1
  - libtiff=4.1.0=h885aae3_6
  - lz4-c=1.9.2=h62dcd97_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mkl=2020.1=216
  - msys2-conda-epoch=20160418=1
  - ninja=1.7.1=0
  - numpy=1.19.1=py37hae9e721_0
  - olefile=0.46=py_0
  - opencv=3.4.2=py37h40b0b35_0
  - openssl=1.1.1g=he774522_1
  - pillow=7.2.0=py37hc826c6e_1
  - pip=20.2=py_0
  - py-opencv=3.4.2=py37hc319ecb_0
  - python=3.7.8=h60c2a47_0_cpython
  - python_abi=3.7=1_cp37m
  - pytorch=1.6.0=py3.7_cuda102_cudnn7_0
  - setuptools=49.2.0=py37hc8dfbb8_0
  - sqlite=3.32.3=he774522_1
  - tk=8.6.10=hfa6e2cd_0
  - torchvision=0.7.0=py37_cu102
  - vc=14.1=h869be7e_1
  - vs2008_runtime=9.0.30729.6161=0
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wheel=0.34.2=py_1
  - wincertstore=0.2=py37_1003
  - xz=5.2.5=h62dcd97_1
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.5=h1f3a1b7_2
  - pip:
    - absl-py==0.9.0
    - attrs==19.3.0
    - backcall==0.2.0
    - bleach==3.1.5
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==7.1.2
    - colorama==0.4.3
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - google-auth==1.20.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.30.0
    - idna==2.10
    - importlib-metadata==1.7.0
    - ipykernel==5.3.4
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - jinja2==2.11.2
    - joblib==0.16.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.6
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - kiwisolver==1.2.0
    - markdown==3.2.2
    - markupsafe==1.1.1
    - matplotlib==3.3.0
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.7
    - nltk==3.5
    - notebook==6.0.3
    - oauthlib==3.1.0
    - packaging==20.4
    - pandas==1.1.0
    - pandocfilters==1.4.2
    - parso==0.7.1
    - pickleshare==0.7.5
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.5
    - protobuf==3.12.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pywin32==228
    - pywinpty==0.5.7
    - pyzmq==19.0.1
    - qtconsole==4.7.5
    - qtpy==1.9.0
    - regex==2020.7.14
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-learn==0.23.1
    - scipy==1.5.2
    - seaborn==0.10.1
    - send2trash==1.5.0
    - six==1.15.0
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - terminado==0.8.3
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tornado==6.0.4
    - tqdm==4.48.0
    - traitlets==4.3.3
    - urllib3==1.25.10
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - zipp==3.1.0